language: csharp
sudo: required
dist: trusty

dotnet: 2.0.3
mono:
  - 5.4.1
  - latest # => "stable release"
  - alpha
  - beta
  - weekly # => "latest commits"
os:
  - linux

script:
  - ./build.sh

matrix:
  allow_failures:
    - mono: latest
    - mono: alpha
    - mono: beta
    - mono: weekly
