language: csharp
sudo: required
dist: trusty

dotnet: 2.0.3
mono:
  - 5.4.1
  - latest # => "stable release"
  - alpha
  - beta
  - weekly # => "latest commits"
os:
  - linux

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

script:
  - ./build.sh

matrix:
  allow_failures:
    - mono: latest
    - mono: alpha
    - mono: beta
    - mono: weekly
